#!/bin/bash

SCRIPT_FOLDER="$HOME/Scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1" 


if [[ -f $SCRIPT_FILE ]]; then
  echo file already exists
  subl $SCRIPT_FILE
else
  echo '#!/bin/bash' > $SCRIPT_FILE
  chmod +x $SCRIPT_FILE
  subl $SCRIPT_FILE
fi


echo '#!/bin/bash' > $SCRIPT_FILE
chmod +x $SCRIPT_FILE
# touch $1

